version: '3.10'

services:
  app:
    build: .
    command: >
      sh -c "
      python manage.py makemigrations marketapp &&
      python manage.py makemigrations usersapp &&
      python manage.py migrate &&
      python manage.py fill_db &&
      python manage.py runserver 0.0.0.0:8000
      "
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/mydatabase
      - DJANGO_SETTINGS_MODULE=M_Network.settings
    depends_on:
      - db
    volumes:
      - repositories:/app/storage
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
volumes:
  postgres_data:
  
  repositories:
    driver: local
